sudo: required
dist: trusty
addons:
  chrome: stable

language: python
python:
  - "3.7"
cache: pip
install:
  - pip install -r requirements.txt
script:
  - # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - python -m unittest -v tallersemana2
  
